### ISSUE TITLE
创建项目异常

### ISSUE THREAD

**Issue by 759325100** [a597873885/webfunny-servers#1]
[2019-09-25T16:01:05.812] [ERROR] errorLog - 
*************** error log start ***************
method: POST
originalUrl:  /server/createNewProject
client ip:  ::1
body: 
{"webMonitorId":1569398465753,"projectName":"测试项目","domain":"localhost:8011","mainDomain":""}
response time: 0
err name: SequelizeDatabaseError
err message: Table 'frondmonitor.project' doesn't exist
err stack: SequelizeDatabaseError: Table 'frondmonitor.project' doesn't exist
    at Query.formatError (E:\殷猛\调研代码\webfunny-servers\node_modules\sequelize\lib\dialects\mysql\query.js:247:16)
    at Query.handler [as onResult] (E:\殷猛\调研代码\webfunny-servers\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.execute (E:\殷猛\调研代码\webfunny-servers\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (E:\殷猛\调研代码\webfunny-servers\node_modules\mysql2\lib\connection.js:408:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (E:\殷猛\调研代码\webfunny-servers\node_modules\mysql2\lib\connection.js:70:12)
    at PacketParser.executeStart (E:\殷猛\调研代码\webfunny-servers\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (E:\殷猛\调研代码\webfunny-servers\node_modules\mysql2\lib\connection.js:77:25)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
*************** error log end ***************

数据库自动创建的表里的名称是projects，但是代码里报project是否为复数原因。

**Comment by a597873885** [comment]
@759325100  目前的这个部署版还是有点问题的，之后会发布一个更完整的版本，就不会有问题了。到时候我会单独通知你

**Comment by 759325100** [comment]
@a597873885 有无可能开源加密的代码？可能会存在二次开发的情况。还是说项目准备后续演化成类似fundebug那样的收费项目。

**Comment by a597873885** [comment]
@759325100  这是个人开发，应该无力演化成那样，只是业务代码，不方便开源出来

**Comment by 759325100** [comment]
@a597873885  也能理解。但是对于想二次开发的我们就很难了。期待项目能尽快正常运行起来。

**Comment by 759325100** [comment]
![image](https://user-images.githubusercontent.com/3062742/65587185-06a58c80-dfb8-11e9-9121-2461e8d32553.png)
![image](https://user-images.githubusercontent.com/3062742/65587242-22109780-dfb8-11e9-9fa8-9e17159ea42b.png)

我创建了一个项目，前端也进行使用，但是后台并无看到响应的错误及日志信息。如您有空也请帮忙瞄一下。谢谢。

**Comment by babaili2008** [comment]
![image](https://user-images.githubusercontent.com/23186202/65594892-2f348300-dfc6-11e9-8d8e-3a76dda11a3a.png)
我部署完了也遇到了问题

**Comment by a597873885** [comment]
@759325100 @babaili2008  两位小伙伴，我修复了创建项目的问题， 拉去最新代码，重新部署一下吧。
